//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerLingus.Helpers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AerLingus_databaseEntities1 : DbContext
    {
        public AerLingus_databaseEntities1()
            : base("name=AerLingus_databaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Flight_Records> Flight_Records { get; set; }
        public virtual DbSet<FR_Batch_Files> FR_Batch_Files { get; set; }
    }
}
