//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerLingus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Flight_Records
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight_Records()
        {
            this.JourneySegments = new HashSet<JourneySegment>();
        }

        //[MinLength(0)]
        [MaxLength(16)]
        [Display(Name ="Identifier Number")]
        public string IdentifierNo { get; set; }

        [Required]
        //[MinLength(1)]
        [MaxLength(2)]
        [Display(Name = "Transaction Type")]
        public string TransactionType { get; set; }

        //[MinLength(0)]
        [MaxLength(30)]
        [Display(Name = "Other FFP Number")]
        public string OtherFFPNo { get; set; }

        //[MinLength(0)]
        [MaxLength(30)]
        [Display(Name = "Other FFP Scheme")]
        public string OtherFFPScheme { get; set; }

        [Required]
        //[MinLength(1)]
        [MaxLength(30)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        //[MinLength(1)]
        [MaxLength(30)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        //[MinLength(0)]
        [MaxLength(100)]
        [Display(Name = "Partner Transaction Number")]
        public string PartnerTransactionNo { get; set; }

        [Display(Name = "Booking Date")]
        public DateTime BookingDate { get; set; }

        [Required]
        [Display(Name = "Departure Date")]
        public string DepartureDate { get; set; }

        [Required]
        //[MinLength(1)]
        [MaxLength(3)]
        [Display(Name = "Origin")]
        public string Origin { get; set; }

        [Required]
        //[MinLength(1)]
        [MaxLength(3)]
        [Display(Name = "Destination")]
        public string Destination { get; set; }

        [Required]
        //[MinLength(1)]
        [MaxLength(2)]
        [Display(Name = "Booking Class")]
        public string BookingClass { get; set; }

        //[MinLength(0)]
        [MaxLength(1)]
        [Display(Name = "Cabin Class")]
        public string CabinClass { get; set; }

        [Required]
        //[MinLength(1)]
        [MaxLength(4)]
        [Display(Name = "Marketing Flight Number")]
        public string MarketingFlightNo { get; set; }

        [Required]
        //[MinLength(1)]
        [MaxLength(2)]
        [Display(Name = "Marketing Airline")]
        public string MarketingAirline { get; set; }

        [Required]
        //[MinLength(1)]
        [MaxLength(4)]
        [Display(Name = "Operating Flight Number")]
        public string OperatingFlightNo { get; set; }

        [Required]
        //[MinLength(1)]
        [MaxLength(2)]
        [Display(Name = "Operating Airline")]
        public string OperatingAirline { get; set; }

        [MinLength(13)]
        [MaxLength(14)]
        [Display(Name = "Ticket Number")]
        public string TicketNo { get; set; }

        //[MinLength(0)]
        [MaxLength(25)]
        [Display(Name = "External Pax ID")]
        public string ExternalPaxID { get; set; }

        //[MinLength(0)]
        [MaxLength(2)]
        [Display(Name = "Coupon Number")]
        public string CouponNo { get; set; }

        [Required]
        [MinLength(1)]
        [MaxLength(6)]
        [Display(Name = "PNR Number")]
        public string PnrNo { get; set; }

        [Range(minimum: 0, maximum: 99999)]
        [Display(Name = "Distance")]
        public long Distance { get; set; }

        [Range(minimum: 0, maximum: 999999999)]
        [Display(Name = "Base Fare")]
        public double BaseFare { get; set; }

        [Range(minimum: 0, maximum: 999999999)]
        [Display(Name = "Discount Base")]
        public double DiscountBase { get; set; }

        [Range(minimum: 0, maximum: 999999999)]
        [Display(Name = "Excise Tax")]
        public double ExciseTax { get; set; }

        //[MinLength(0)]
        [MaxLength(1)]
        [Display(Name = "Customer Type")]
        public string CustomerType { get; set; }

        //[MinLength(0)]
        [MaxLength(100)]
        [Display(Name = "Promotion Code")]
        public string PromotionCode { get; set; }

        //[MinLength(0)]
        [MaxLength(3)]
        [Display(Name = "Ticket Currency")]
        public string TicketCurrency { get; set; }

        //[MinLength(0)]
        [MaxLength(3)]
        [Display(Name = "Target Currency")]
        public string TargetCurrency { get; set; }

        [Range(minimum: 0, maximum: 9999999999)]
        [Display(Name = "Exchange Rate")]
        public double ExchangeRate { get; set; }

        //[MinLength(0)]
        [MaxLength(10)]
        [Display(Name = "Fare Basis")]
        public string FareBasis { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JourneySegment> JourneySegments { get; set; }
    }
}
