//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerLingus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandbackRecord
    {
        public int ID { get; set; }
        public string TransactionType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DepartureDate { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string BookingClass { get; set; }
        public string CabinClass { get; set; }
        public string MarketingFlightNo { get; set; }
        public string MarketingAirline { get; set; }
        public string OperatingFlightNo { get; set; }
        public string OperatingAirline { get; set; }
        public string TicketNo { get; set; }
        public string CouponNo { get; set; }
        public string PNRNo { get; set; }
        public string FareBasis { get; set; }
        public string Status { get; set; }
        public Nullable<int> DownloadCounter { get; set; }
        public string Description { get; set; }
    }
}
