//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerLingus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaggingRejectedUA
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> DownloadCounter { get; set; }
        public string Header { get; set; }
        public string Record { get; set; }
        public string Footer { get; set; }
    }
}
